# Generated by Django 3.1.5 on 2021-01-27 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('asignee', models.CharField(max_length=50)),
                ('job_id', models.CharField(max_length=50)),
                ('date_due', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.date')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('title', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('dates', models.ManyToManyField(to='api.Date')),
            ],
        ),
    ]
