# Generated by Django 3.1.5 on 2021-01-31 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='date_due',
            new_name='date',
        ),
    ]
