# Generated by Django 3.1.5 on 2021-02-03 23:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210201_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='due_dates',
        ),
        migrations.AddField(
            model_name='event',
            name='due_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.date'),
            preserve_default=False,
        ),
    ]
