# Generated by Django 3.1.5 on 2021-02-06 17:51

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210203_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='due_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='event',
            name='length',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.CharField(default='12:00', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='end date'),
        ),
    ]
