# Generated by Django 3.1.5 on 2021-02-16 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210214_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='asignee',
            new_name='assignee',
        ),
    ]
